---
# Data
train_path: # TODO: add path to training images e.g. ./data/train
train_validation_split: 0.7
test_path: # TODO: Add path to test images  e.g. ./data/test
file_formats:
  - '.jpg'
batch_size: 128

# Training
epochs: 10
learning_rate: 1.0e-2

# Model
model_path: # Optional: Model load path
