---
# Data
train_path: ../data/images/train/ # TODO: add path to training images e.g. ./data/train
train_validation_split: 0.7
test_path: ../data/images/test/ # TODO: Add path to test images  e.g. ./data/test
file_formats:
  - .jpg
batch_size: 128

# Training
epochs: 1
learning_rate: 1.0e-2

# Model
model_path: # Optional: Model load path

# Metrics
train_metrics:
  - loss
  - accuracy
  - precision
  - recall
validation_metrics:
  - loss
  - accuracy
  - precision
  - recall
test_metrics:
  - loss
  - accuracy
  - precision
  - recall
