name: Python Tests

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          make .env
          . .env/bin/activate
          make install
          make install-test
      - name: Lint with flake8
        run: |
          . .env/bin/activate
          # stop the build if there a-re Python syntax errors or undefined names
          flake8 src/ main.py --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 src/ main.py --count --exit-zero --max-complexity=10 --statistics
      - name: Lint with pylint
        run: |
          . .env/bin/activate
          pylint src/ main.py
      - name: Test with pytest
        run: |
          . .env/bin/activate
          pytest -v
